we are in dir /home/jie/human-eval-comm
device:  cuda
----------------------problem name: HumanEval/136--------------------------------
using codellama-13B-instruct-v6 to generate response
HumanEval/136---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f1450>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/136---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f4110>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/136---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f6e90>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/136---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x149469705d90>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
----------------------problem name: HumanEval/137--------------------------------
using codellama-13B-instruct-v6 to generate response
HumanEval/137---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f4290>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/137---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494697051d0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/137---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x149469719150>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/137---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x149469707910>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
----------------------problem name: HumanEval/138--------------------------------
using codellama-13B-instruct-v6 to generate response
HumanEval/138---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f2810>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/138---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f5d90>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/138---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x149469720a10>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/138---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14946971a110>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/138---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f5c90>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
----------------------problem name: HumanEval/139--------------------------------
using codellama-13B-instruct-v6 to generate response
HumanEval/139---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x149469706890>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/139---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x149469722dd0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/139---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f68d0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/139---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f38d0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
----------------------problem name: HumanEval/140--------------------------------
using codellama-13B-instruct-v6 to generate response
HumanEval/140---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14946971a650>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/140---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x149469720dd0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/140---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f2810>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/140---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1494696f5ad0>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
HumanEval/140---------Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14946aa9b790>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
----------------------problem name: HumanEval/141--------------------------------
using codellama-13B-instruct-v6 to generate response
slurmstepd: error: *** JOB 35236112 ON ng30711 CANCELLED AT 2024-09-26T12:41:01 DUE TO TIME LIMIT ***
